
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndgcmicucmrorryywsyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kZ2NtaWN1Y21yb3JyeXl3c3lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NDU5MTgsImV4cCI6MjA2MTEyMTkxOH0.sN9fcwkBL4lIIOk_NaNIdpJ-bNpZZQ5Jtv5NexUh4as";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
